defaults:
  - _self_

seed: 42
device: "cuda"
dataset_artifact_name: "cube"
batch_size: 128
n_annealing_epochs: 1
start_kl_scaling_factor: 0.1
end_kl_scaling_factor: 0.1
min_mask: 0.1
max_mask: 0.9
epochs: 1000
output_artifact_aliases: []

pointnet:
  identity_network_num_cells: [20,20]
  identity_size: 20
  feature_map_encoder_num_cells: [500]
  output_size: 40
  max_embedding_norm: 1.0

partial_vae:
  latent_size: 20
  encoder_num_cells: [500, 500, 200]
  decoder_num_cells: [200, 500, 500]
  patience: 5
  lr: 0.001
  kl_scaling_factor: 0.001
  max_masking_probability: 0.9

classifier:
  lr: 0.001
  patience: 5
  num_cells: [128, 128]
  dropout: 0.3
  classifier_loss_scaling_factor: 1.0
