pretrained_model_artifact_name: "pretrain_covert2023-AFAContext_split_1:latest"
batch_size: 128
lr: 0.001
hard_budget: 20
nepochs: 250
patience: 5

hidden_units: [128,128]
dropout: 0.3
activations: 'ReLU'
flag_drop_out: True
flag_only_output_layer: False