epochs: 100
checkpoint: "pretrain_zannone2019_mnist.ckpt"
lr: 0.001

dataset:
  name: "mnist"
  n_features: 784 # MNIST IMAGE SIZE, DO NOT CHANGE
dataloader:
  batch_size: 100
  train_ratio: 0.8
  num_workers: 1
pointnet:
  type: "pointnetplus"
  identity_network_num_cells: [20,20]
  identity_size: 20
  element_encoder_num_cells: [500]
  output_size: 20
encoder:
  num_cells: [500, 500, 200]
partial_vae:
  latent_size: 20
  decoder_num_cells: [200, 500, 500]
  decoder_last_layer_sigmoid: True
classifier:
  output_size: 10 # mnist classes
  num_cells: [64, 64]
wandb:
  entity: "valterschutz-chalmers-university-of-technology"
  project: "pretrain-zannone2019-mnist"
device: "cuda"
