epochs: 100
checkpoint: "pretrain_zannone2019_cube.ckpt"
lr: 0.0001

dataset:
  name: "cube"
  n_features: 20
  size: 100000
  sigma: 0.01
  seed: 42
dataloader:
  batch_size: 128
  train_ratio: 0.8
  num_workers: 1
pointnet:
  identity_network_num_cells: [20, 20, 20]
  identity_size: 20
  element_encoder_num_cells: [20, 20, 20]
  output_size: 20
encoder:
  output_size: 200
  num_cells: [500]
partial_vae: # TODO
  latent_size: 100
  mu_net_num_cells: []
  logvar_net_num_cells: []
  decoder_num_cells: [500, 200]
classifier:
  output_size: 8 # cube classes
  num_cells: []
wandb:
  entity: "valterschutz-chalmers-university-of-technology"
  project: "pretrain-zannone2019-cube"
device: "cuda"
