epochs: 100
checkpoint: "pretrain_zannone2019_cube.ckpt"
lr: 0.001

dataset:
  name: "cube"
  n_features: 20
  size: 100000
  sigma: 0.01
  seed: 42
dataloader:
  batch_size: 128
  train_ratio: 0.8
  num_workers: 1
pointnet: # 21 -> 20 -> 20
  input_size: 21
  output_size: 20
  num_cells: [20]
encoder:
  output_size: 20
  num_cells: [500, 200] # 20 -> 500 -> 200 -> 20
partial_vae:
  latent_size: 20
  mu_net_num_cells: [] # 20 -> 20
  logvar_net_num_cells: [] # 20 -> 20
  decoder_num_cells: [500, 200] # 20 -> 500 -> 200 -> 20
classifier: # 20 -> onehot(8)
  output_size: 8 # cube classes
  num_cells: []
wandb:
  entity: "valterschutz-chalmers-university-of-technology"
  project: "pretrain-zannone2019-cube"
device: "cuda"
