device: "cpu"
generative_batch_size: 50

dataset:
  name: "cube"
  train_path: "data/cube/apr14_train_small.pt"
  val_path: "data/cube/apr14_val.pt"
  n_features: 20
  bounded_0_1: False

acquisition_cost: 0.05
batch_size: 4
n_batches: 100

agent:
  lr: 0.001
  update_tau: 0.01

wandb:
  entity: "valterschutz-chalmers-university-of-technology"
  project: "train-zannone2019"

eval_episodes: 10
eval_max_steps: 100

afa_method_save_name: "afa_method_zannone2019.pt"
