pretrain_shim2018_config: "pretrain_shim2018.yml"
checkpoint: "shim2018.pth"

dataset:
  size: 10000
  sigma: 0.01
  seed: 42

mdp:
  acquisition_cost: 0.05

agent:
  lr: 0.001
  update_tau: 0.001
  eps_init: 1.0
  eps_end: 0.1
  eps_episodes: 5000

n_episodes: 10000
device: "cuda"
eval_every_n_episodes: 500
eval_episodes: 100

wandb:
  entity: "valterschutz-chalmers-university-of-technology"
  project: "train-shim2018"
