pretrain_shim2018_config: "pretrain_shim2018.yml"
checkpoint: "shim2018.pth"

dataset:
  size: 100000
  sigma: 0.01
  seed: 42

mdp:
  acquisition_cost: 0.05

agent:
  lr: 0.001
  update_tau: 0.001
  eps: 0.1

n_episodes: 100000
device: "cuda"
eval_every_n_episodes: 100
eval_episodes: 100

wandb:
  entity: "valterschutz-chalmers-university-of-technology"
  project: "train-shim2018"
