device: "cpu"
generative_batch_size: 50
n_generative_samples: 1000

dataset:
  name: "cube"
  train_path: "data/cube/apr15_train_100.pt"
  val_path: "data/cube/apr15_val_1000.pt"
  n_features: 20
  bounded_0_1: False

acquisition_cost: 0.05
# acquisition_cost: 0.001
batch_size: 4
n_agents: 2
n_batches: 100000

agent:
  lr: 0.001
  # update_tau: 0.01

wandb:
  entity: "valterschutz-chalmers-university-of-technology"
  project: "train-zannone2019"

eval_episodes: 10
eval_max_steps: 30
eval_every_n_batches: 1000

afa_method_save_name: "afa_method_zannone2019.pt"
