pretrain_shim2018_config: "pretrain_shim2018.yml"
afa_method_save_name: "afa_method_shim2018.pt"
dataset_save_name: "dataset_cube.pt"

dataset:
  size: 10000
  sigma: 0.01
  seed: 42

mdp:
  acquisition_cost: 0.05
  invalid_action_cost: 42 # since invalid actions should never be selected, this should have no impact

embedder_classifier:
  lr: 0.001

agent:
  lr: 0.001
  update_tau: 0.001
  eps_init: 1.0
  eps_end: 0.1
  eps_steps: 5000
  replay_buffer_batch_size: 128
  replay_buffer_size: 500000
  num_optim: 4 # how many times to sample from replay buffer for each batch of data received
  replay_buffer_alpha: 0.0 # turn off prioritization for now
  replay_buffer_beta: 0.5

n_batches: 16
n_agents: 2
batch_size: 4
device: "cuda"
eval_every_n_batches: 101
eval_episodes: 100
eval_max_steps: 30


wandb:
  entity: "valterschutz-chalmers-university-of-technology"
  project: "train-shim2018"
