hydra:
  searchpath:
    - file://extra/conf
    - file://extra/conf/components
    - file://extra/conf/global

defaults:
  - train_random_dummy
  - hydra: custom
  - initializer: ???
  - unmasker: ???
  - dataset_key: ???
  - _self_
  - optional experiment@_global_: ${dataset_key}
  - override hydra/job_logging: output_dir_colorlog
  - override hydra/hydra_logging: colorlog
  - override hydra/launcher: custom_slurm
