latency-wait: 30 # seconds

default-resources:
    runtime: 120 # minutes
    slurm_partition: vera
    slurm_account: C3SE2025-1-14

set-resources:
    train_soft_budget_method:
        runtime: 600
        cpus_per_task: 1
        mem_mb: 4000

    eval_soft_budget_method:
        runtime: 600
        cpus_per_task: 1
        mem_mb: 4000

    download_soft_budget_eval_result:
        runtime: 60
        cpus_per_task: 1
        mem_mb: 4000

    combine_soft_budget_eval_result:
        runtime: 60
        cpus_per_task: 1
        mem_mb: 4000

    soft_budget_plot:
        runtime: 60
        cpus_per_task: 1
        mem_mb: 4000
