# reward_method set in higher config
pq_module:
  n_hiddens: [64,32,16] # kachuee2019 implementation for Diabetes
  p_dropout: 0.5 # kachuee2019 implementation
predictor_lr: 1e-3 # kachuee2019 implementation
mcdrop_samples: 100 # kachuee2019 implementation

dataset_artifact_name: "cube_split_1:tmp"
n_agents: 1 # kachuee2019 implementation
hard_budget: 5 # recommended: 3, 5, 10
agent:
  eps_init: 1.0 # kachuee2019 implementation
  eps_end: 0.1 # kachuee2019 implementation
  eps_annealing_num_batches: 15000 # kachuee2019 implementation, same as `n_batches`

  replay_buffer_batch_size: 128 # kachuee2019 implementation
  replay_buffer_size: 20000 # kachuee2019 paper, 1000*n_features

  num_optim: 1 # kachuee2019 implementation
  max_grad_norm: 1
  lr: 1e-3 # kachuee2019 implementation
  update_tau: 0.001 # kachuee2019 implementation

  loss_function: "l2" # kachuee2019 implementation
  delay_value: true # kachuee2019 implementation
  double_dqn: true # kachuee2019 implementation

  # gamma set by higher config
# n_batches: 10000 # kachuee2019 implementation, 1000 episodes
n_batches: 1000000 # kachuee2019 implementation, 1000 episodes
batch_size: 1 # kachuee2019 implementation
eval_every_n_batches: 1000 # kachuee2019 implementation, every 100 episodes
eval_max_steps: 9001
n_eval_episodes: 512 # kachuee2019 implementation
# device set by higher config
# seed set by higher config
# output_artifact_aliases set by higher config
evaluate_final_performance: true
eval_only_n_samples: null
