hydra:
  searchpath:
    - file://conf/global

defaults:
  - _self_
  - dataset@_global_: cube
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - override hydra/launcher: custom_slurm

device: cuda
seed: 42
output_artifact_aliases: ["tmp"]
