hydra:
  searchpath:
    - file://extra/conf
    - file://extra/conf/global

defaults:
  - train_permutation
  - hydra: custom
  - initializer: ???
  - unmasker: ???
  - dataset_key: ???
  - _self_
  - optional experiment@_global_: ${dataset_key}
  - override hydra/job_logging: output_dir_colorlog
  - override hydra/hydra_logging: colorlog
  - override hydra/launcher: custom_slurm

# Same for every dataset key; no experiment file overrides it.
batch_size: 128

selector:
  lr: 0.001
  nepochs: 250
  num_cells: [128, 128]
  patience: 5

classifier:
  lr: 0.001
  nepochs: 250
  num_cells: [128, 128]
