hydra:
  searchpath:
    - file://conf
    - file://conf/components
    - file://conf/global

defaults:
  - train_odin
  - hydra: custom
  - initializer: ???
  - unmasker: ???
  - dataset_key: ???
  - /components/mdps@mdp: default
  - /components/rl_training_loops@rl_training_loop: default
  - _self_
  - optional experiment@_global_: ${dataset_key}
  - override hydra/job_logging: output_dir_colorlog
  - override hydra/hydra_logging: colorlog
  - override hydra/launcher: custom_slurm

# mdp and rl_training_loop set as components

agent:
    lmbda: 0.75 # not specified by odin, same as jafa

    clip_epsilon: 0.2 # not specified by odin
    entropy_bonus: True # not specified by odin
    entropy_coef: 0.01 # not specified by odin
    critic_coef: 1.0 # not specified by odin
    loss_critic_type: "smooth_l1" # not specified by odin

    num_epochs: 1 # same as jafa
    lr: 1e-3 # not specified by odin
    max_grad_norm: 9001 # not specified by odin

    # value_num_cells: [32, 32] # same complexity as jafa
    value_num_cells: [] # odin
    value_dropout: 0.0 # not specified by odin
    # policy_num_cells: [32, 32] # same complexity as jafa
    policy_num_cells: [] # odin
    policy_dropout: 0.0 # not specified by odin
    gamma: 1.0
additional_generation_fraction: 0.0
generation_batch_size: 100
