epochs: 1000

dataloader:
  batch_size: 128
  num_workers: 1

lr: 0.001

wandb:
  entity: "valterschutz-chalmers-university-of-technology"
  project: "train-masked-mlp-classifier"

device: "cuda"

max_masking_probability: 0.9
