hydra:
  searchpath:
    - file://extra/conf/global

defaults:
  - hydra: custom
  - _self_
  - dataset@_global_: cube
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - override hydra/launcher: custom_slurm

aco:
  k_neighbors: 5
  acquisition_cost: 0.05
  hide_val: 0.0  # Use 0 for consistency with MLP training
  evaluate_final_performance: true
  eval_only_n_samples: null

seed: 42
device: "cpu"
cost_param: ???
hard_budget: ???
save_path: ???
dataset_artifact_name: ???
classifier_bundle_path: ???
initializer_type: "aaco"
unmasker_type: "one_based_index"
smoke_test: false
