hydra:
  searchpath:
    - file://conf/global

defaults:
  - _self_
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - override hydra/launcher: custom_slurm

dataset_artifact_name: cube_split_1:tmp
seed: 42
hard_budget: 5
output_artifact_aliases: ["tmp"]
