class_weights: !!python/object/apply:torch._utils._rebuild_tensor_v2
- !!python/object/apply:torch.storage._load_from_bytes
  - !!binary |
    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
    Z2UKcQFYDQAAADE3Mzg3NTMxODk5NjhxAlgDAAAAY3B1cQNLCE50cQRRLoACXXEAWA0AAAAxNzM4
    NzUzMTg5OTY4cQFhLggAAAAAAAAAL8MIPmyy6z0NsxU+PKn+PS/DCD44GAc+ADbZPQfL3z0=
- 0
- !!python/tuple
  - 8
- !!python/tuple
  - 1
- false
- !!python/object/apply:collections.OrderedDict
  - []
hidden_dims:
- 128
- 64
- 32
input_dim: 20
learning_rate: 0.001
output_dim: 2
