pretrained_model_artifact_name: "pretrain_gadgil2023-imagenette_split_1:latest"

batch_size: 128
lr: 0.00001
min_lr: 0.00000001
hard_budget: 15
nepochs: 250
patience: 3
eps: 0.05
eps_decay: 0.2
eps_steps: 10
