dataset_artifact_name: "FashionMNIST_split_1:tmp"
batch_size: 128 # shim2018 paper
epochs: 200
limit_train_batches: null
limit_val_batches: null

lr: 1e-3
min_masking_probability: 0.75
max_masking_probability: 0.99
pq_module:
  n_hiddens: [512,512,128,64] # kachuee2019 for MNIST
  p_dropout: 0.5 # kachuee2019 implementation
