hydra:
  searchpath:
    - file://extra/conf
    - file://extra/conf/global

defaults:
  - plot_total_time
  - hydra: custom
  - /scripts/plotting/common@plotting: default
  - _self_
  - optional experiment@_global_: null
  - override hydra/job_logging: output_dir_colorlog
  - override hydra/hydra_logging: colorlog

output_folder: ???
input: null
formats:
  - pdf
