hydra:
  searchpath:
    - file://extra/conf
    - file://extra/conf/global

defaults:
  - hydra: custom
  - optional /components/initializers@initializer: ???
  - /components/unmaskers@unmasker: ???
  - /components/masked_pretraining@_global_: default
  - /components/masking_probabilities@_global_: simple
  - _self_
  - optional experiment@_global_: ???
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - override hydra/launcher: custom_slurm

supervised_learning:
  early_stopping_min_delta: 1e-3

train_dataset_bundle_path: ???
val_dataset_bundle_path: ???
save_path: ???
device: cuda

# batch size set to shim2018 paper default, since kachuee2019 does not specify it

lr: 1e-3
pq_module:
  n_hiddens: [64,32,16] # kachuee2019 implementation for Diabetes
  p_dropout: 0.5 # kachuee2019 implementation
  use_feature_mask: false # like original paper

seed: null
use_wandb: false
smoke_test: false
