# Illustrative site only: replace partitions/accounts in site.yaml.
executor: slurm
jobs: 9001
latency-wait: 30
default-resources:
  runtime: 120
  mem_mb: 4000
  cpus_per_task: 1
set-resources:
  train_method:
    runtime: 600
    cpus_per_task: 8
  eval_method:
    runtime: 600
    cpus_per_task: 8
config:
  execution_site_file: workflow/profiles/site/examples/mixed-gpus/site.yaml
