executor: slurm
jobs: 9001
latency-wait: 30 # seconds

default-resources:
  runtime: 120 # minutes
  mem_mb: 0 # Only memory attribute that works

set-resources:
  pretrain_model:
    runtime: 600 # 10 hours
  train_method:
    runtime: 600 # 10 hours
  eval_method:
    runtime: 600 # 10 hours

config:
  execution_site_file: workflow/profiles/site/alvis/site.yaml
