epochs: 1000
lr: 0.001
verbose: False
max_masking_probability: 0.9
validation_masking_probability: 0.0
recon_loss_type: "squared error"
kl_scaling_factor: 0.001

dataloader:
  batch_size: 100
pointnet:
  naive_identity_type: "1D"
  type: "pointnetplus" # ODIN paper does not mention which type they use
  identity_network_num_cells: [20,20] # just a guess
  identity_size: 20 # EDDI paper
  feature_map_encoder_num_cells: [500] # EDDI paper
  output_size: 40 # always twice as large as latent size according to EDDI paper
encoder:
  num_cells: [500, 200] # ODIN paper
  # num_cells: [500, 500, 200] # EDDI paper
partial_vae:
  latent_size: 20 # EDDI paper
  decoder_num_cells: [200, 500, 500] # EDDI paper
classifier:
  num_cells: [64, 64] # just a guess

wandb:
  entity: "valterschutz-chalmers-university-of-technology"
  project: "pretrain-zannone2019-cube"

device: "cuda"
