

agent:
  gamma: 1
  lmbda: 0.95
  clip_epsilon: 0.2
  entropy_bonus: True
  entropy_coef: 0.0001
  critic_coef: 1.0
  loss_critic_type: "smooth_l1"
  lr: 0.001
  max_grad_norm: 10
  sub_batch_size: 128
  num_epochs: 4

env:
  hard_budget: 10

wandb:
  entity: "valterschutz-chalmers-university-of-technology"
  project: "train-zannone2019"

n_batches: 10000
n_agents: 128
batch_size: 512
device: "cuda"
eval_max_steps: 9001
eval_every_n_batches: 100
n_eval_episodes: 100

generative_batch_size: 128
