device: "cuda"
generative_batch_size: 128

n_batches: 20000
n_agents: 128
batch_size: 512

agent:
  lr: 0.001
  lmbda: 0.5
  clip_epsilon: 0.2
  entropy_bonus: True
  entropy_coef: 0.01

env:
  hard_budget: 10

wandb:
  entity: "valterschutz-chalmers-university-of-technology"
  project: "train-zannone2019"

eval_episodes: 100
eval_max_steps: 30
eval_every_n_batches: 1000
