hydra:
  searchpath:
    - file://conf/global

defaults:
  - _self_
  - dataset@_global_: cube
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - override hydra/launcher: valter_slurm

reward_method: "Bayesian-L1" # used in the original implementation
agent:
  gamma: 1.0
device: cuda
seed: 42
output_artifact_aliases: ["tmp"]
