pretrained_model_artifact_name: "pretrain_shim2018-cube_split_1:tmp"
evaluate_final_performance: true
eval_only_n_samples: null
n_agents: 128 # shim2018 paper
hard_budget: 5 # recommended: 3, 5, 10
agent:
  eps_annealing_num_batches: 1000 
  replay_buffer_size: 1000000
  replay_buffer_batch_size: 128
  replay_buffer_beta_annealing_num_batches: ${n_batches}
  num_optim: 4 # shim2018 paper
  eps_init: 1.0 # shim2018 paper
  eps_end: 0.1 # shim2018 paper
  lr: 1e-3
  update_tau: 0.005
  action_value_num_cells: [32, 32] # shim2018 paper
  action_value_dropout: 0.0
n_batches: 100 # medium
batch_size: 512 # shim2018 paper
eval_every_n_batches: 500
eval_max_steps: 9001
n_eval_episodes: 100

pretrained_model_lr: 1e-3
