dataset_types: ["shim2018cube"]
dataset_splits: [1]
seeds: [1]
hard_budgets:
  AFAContext: [5]
pretrain_job_path: "src/afa_rl/shim2018/slurm/pretrain_shim2018_job.sh"
train_job_path: "src/afa_rl/shim2018/slurm/train_shim2018_job.sh"
