epochs: 3000
# epochs: 1

dataloader:
  batch_size: 128
  num_workers: 1
encoder:
  output_size: 128
  reading_block_cells: [128, 128]
  writing_block_cells: [128, 128]
  memory_size: 128
  processing_steps: 10
classifier:
  num_cells: [128, 128, 128]
embedder_classifier:
  lr: 0.0001
max_masking_probability: 0.99
wandb:
  entity: "valterschutz-chalmers-university-of-technology"
  project: "pretrain-shim2018"
device: "cuda"
