epochs:
  cube: 3000
  AFAContext: 3000
  MNIST: 20
  diabetes: 30
  physionet: 50

dataloader:
  batch_size:
    cube: 128
    AFAContext: 128
    MNIST: 128
    diabetes: 128
    physionet: 128
  num_workers: 1
encoder:
  output_size:
    cube: 16
    AFAContext: 16
    MNIST: 128
    diabetes: 16
    physionet: 16
  reading_block_cells:
    cube: [32, 32]
    AFAContext: [32, 32]
    MNIST: [128, 128]
    diabetes: [32, 32]
    physionet: [32, 32]
  writing_block_cells:
    cube: [32, 32]
    AFAContext: [32, 32]
    MNIST: [128, 128]
    diabetes: [32, 32]
    physionet: [32, 32]
  memory_size:
    cube: 16
    AFAContext: 16
    MNIST: 128
    diabetes: 16
    physionet: 16
  processing_steps: 5
  dropout: 0.1
classifier:
  num_cells:
    cube: [32, 32]
    AFAContext: [32, 32]
    MNIST: [128, 128]
    diabetes: [32, 32]
    physionet: [32, 32]
embedder_classifier:
  lr:
    cube: 0.001
    AFAContext: 0.001
    MNIST: 0.001
    diabetes: 0.001
    physionet: 0.0001
max_masking_probability:
  cube: 0.9
  AFAContext: 0.9
  MNIST: 0.99
  diabetes: 0.9
  physionet: 0.9
wandb:
  entity: "valterschutz-chalmers-university-of-technology"
  project: "pretrain-shim2018"
device: "cuda"
