# epochs: 2000
epochs: 1

dataloader:
  batch_size: 128
  num_workers: 1
encoder:
  output_size: 16
  reading_block_cells: [32, 32]
  writing_block_cells: [32, 32]
  memory_size: 16
  processing_steps: 5
classifier:
  num_cells: [32, 32]
embedder_classifier:
  lr: 0.001
wandb:
  entity: "valterschutz-chalmers-university-of-technology"
  project: "pretrain-shim2018"
device: "cuda"
