pretrained_model:
  lr: 0.001

agent:
  lr: 0.001
  update_tau: 0.005
  eps_init: 1.0
  eps_end: 0.1
  eps_steps:
    cube: 5000
    AFAContext: 5000
    MNIST: 5000
    diabetes: 5000
    physionet: 5000
  replay_buffer_batch_size: 128
  replay_buffer_size: 1000000
  num_optim: 4 # how many times to sample from replay buffer for each batch of data received
  replay_buffer_alpha: 0.6
  replay_buffer_beta_init: 0.4
  replay_buffer_beta_end: 1
  max_grad_norm: 10
  delay_value: true
  double_dqn: true
  init_random_frames: 0

n_batches:
  cube: 10000
  AFAContext: 10000
  MNIST: 10000
  diabetes: 10000
  physionet: 10000
n_agents: 128
batch_size: 512
device: "cuda"
eval_max_steps: 9001
eval_every_n_batches:
  cube: 500
  AFAContext: 500
  MNIST: 500
  diabetes: 500
  physionet: 500
n_eval_episodes: 100
activate_joint_training_after_n_batches:
  cube: 0
  AFAContext: 0
  MNIST: 0
  diabetes: 0
  physionet: 0


wandb:
  entity: "valterschutz-chalmers-university-of-technology"
  project: "train-shim2018"
