acquisition_cost: 0.05

embedder_classifier:
  lr: 0.001

agent:
  lr: 0.001
  update_tau: 0.05
  eps_init: 1.0
  eps_end: 0.1
  eps_steps: 5000
  replay_buffer_batch_size: 128
  # replay_buffer_size: 512 # same as batch size because original paper does not use replay buffer
  replay_buffer_size: 1000000
  num_optim: 4 # how many times to sample from replay buffer for each batch of data received
  # replay_buffer_alpha: 0.0 # Disable prioritized replay buffer
  replay_buffer_alpha: 0.6
  replay_buffer_beta: 0.4

n_batches: 10000
n_agents: 128
batch_size: 512
device: "cuda"
eval_every_n_batches: 1000
eval_episodes: 100
eval_max_steps: 30


wandb:
  entity: "valterschutz-chalmers-university-of-technology"
  project: "train-shim2018"
