latency-wait: 30 # seconds

default-resources:
    runtime: 120 # minutes
    slurm_partition: alvis
    slurm_account: NAISS2024-22-1677

set-resources:
    train_soft_budget_method:
        runtime: 6000 # 100 hours
        mem_mb: 0 # Only memory attribute that works
        slurm_extra: "--gres=gpu:T4:1"
