hydra:
  searchpath:
    - file://conf/global

defaults:
  - _self_
  - dataset@_global_: cube
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - override hydra/launcher: custom_slurm

# Default settings below, but fine-tune for each dataset
dataset_artifact_name: "cube_split_1:tmp"
batch_size: 128
epochs: 1000
limit_train_batches: null
limit_val_batches: null

lr: 1e-3
min_masking_probability: 0.0
max_masking_probability: 0.9
pointnet:
  type: "pointnetplus" # ODIN paper does not mention which type they use
  identity_network_num_cells: [128,128] # just a guess
  identity_network_dropout: 0.1
  identity_size: 128 # EDDI paper
  feature_map_encoder_num_cells: [128,128] # EDDI paper
  feature_map_encoder_dropout: 0.1
  output_size: 128 # always twice as large as latent size according to EDDI paper
encoder:
  num_cells: [128, 128] # ODIN paper
  dropout: 0.1
partial_vae:
  latent_size: 64
  decoder_num_cells: [128, 128]
  decoder_dropout: 0.1
classifier:
  num_cells: [128, 128]
  dropout: 0.1
recon_loss_type: "squared_error"
kl_scaling_factor: 0.001

