dataset_artifact_name: "MNIST_split_1:tmp"
batch_size: 100 # EDDI
epochs: 200
limit_train_batches: null
limit_val_batches: null

lr: 1e-3
min_masking_probability: 0.75
max_masking_probability: 0.99
pointnet:
  type: "pointnetplus" # ODIN paper does not mention which type they use
  identity_size: 20 # EDDI
  max_embedding_norm: 1.0
  feature_map_encoder_num_cells: [500] # EDDI
  feature_map_encoder_dropout: 0.0
  output_size: 40 # always twice as large as latent size according to EDDI paper
encoder:
  num_cells: [500, 500, 200] # EDDI
  dropout: 0.1
partial_vae:
  latent_size: 20 # EDDI
  decoder_num_cells: [200, 500, 500] # EDDI
  decoder_dropout: 0.0
classifier:
  num_cells: [128, 128] # same for all methods!
  dropout: 0.0
recon_loss_type: "squared_error"
kl_scaling_factor: 0.01
classifier_loss_scaling_factor: 100
