dataset_types: ["cube", "AFAContext"]
dataset_splits: [1,2]
seeds: [42]
hard_budgets:
  cube: [5, 10, 20]
  AFAContext: [5, 10, 20]
pretrain_job_path: "src/afa_discriminative/slurm/pretrain_gadgil2023_job.sh"
train_job_path: "src/afa_discriminative/slurm/train_gadgil2023_job.sh"
