eval_artifact_names:
  - "aaco-cube_split_1-builtin:latest"
  - "aaco-cube_split_2-builtin:latest"
  - "aaco-cube_split_3-builtin:latest"
  - "aaco-cube_split_4-builtin:latest"
  - "aaco-cube_split_5-builtin:latest"
  - "aaco-AFAContext_split_1-builtin:latest"
  - "aaco-AFAContext_split_2-builtin:latest"
  - "aaco-AFAContext_split_3-builtin:latest"
  - "aaco-AFAContext_split_4-builtin:latest"
  - "aaco-AFAContext_split_5-builtin:latest"
  - "aaco-MNIST_split_1-builtin:latest"
  - "aaco-MNIST_split_2-builtin:latest"
  - "aaco-MNIST_split_3-builtin:latest"
  - "aaco-MNIST_split_4-builtin:latest"
  - "aaco-MNIST_split_5-builtin:latest"
  - "aaco-FashionMNIST_split_1-builtin:latest"
  - "aaco-FashionMNIST_split_2-builtin:latest"
  - "aaco-FashionMNIST_split_3-builtin:latest"
  - "aaco-FashionMNIST_split_4-builtin:latest"
  - "aaco-FashionMNIST_split_5-builtin:latest"
  - "aaco-diabetes_split_1-builtin:latest"
  - "aaco-diabetes_split_2-builtin:latest"
  - "aaco-diabetes_split_3-builtin:latest"
  - "aaco-diabetes_split_4-builtin:latest"
  - "aaco-diabetes_split_5-builtin:latest"
  - "aaco-miniboone_split_1-builtin:latest"
  - "aaco-miniboone_split_2-builtin:latest"
  - "aaco-miniboone_split_3-builtin:latest"
  - "aaco-miniboone_split_4-builtin:latest"
  - "aaco-miniboone_split_5-builtin:latest"
  - "aaco-physionet_split_1-builtin:latest"
  - "aaco-physionet_split_2-builtin:latest"
  - "aaco-physionet_split_3-builtin:latest"
  - "aaco-physionet_split_4-builtin:latest"
  - "aaco-physionet_split_5-builtin:latest"
metric_keys_and_descriptions:
  - key: accuracy_all
    description: Accuracy
    ylim: [0.0, 1.0]
  - key: f1_all
    description: "F1 score"
    ylim: [0.0, 1.0]
  - key: bce_all
    description: "Binary Cross-Entropy"
    ylim: null
