eval_artifact_config_path: "conf/plot/lists/tmp.yaml"
metric_keys_and_descriptions:
  - key: accuracy_all
    description: Accuracy
    # ylim: [0.0, 1.0]
    ylim: []
  - key: f1_all
    description: "F1 score"
    # ylim: [0.0, 1.0]
    ylim: []
  - key: bce_all
    description: "Binary Cross-Entropy"
    ylim: null
max_workers: 8
