program: scripts/train_methods/train_kachuee2019.py
name: train_kachuee2019_MNIST
method: grid
# metric:
#   goal: maximize
#   name: mean_final_eval_reward
parameters:
  dataset_artifact_name:
    values:
      - "MNIST_split_1:Jun11"
      # - "MNIST_split_2:Jun11"
  hard_budget:
    values:
      - 10
      # - 20
      # - 30

command:
  - ${env}
  - python
  - ${program}
  - "-m" # hydra multirun, enables slurm
  - ${args_no_hyphens}

