hydra:
  searchpath:
    - file://conf/global

defaults:
  - _self_
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - override hydra/launcher: custom_slurm


trained_method_artifact_name: "train_shim2018-cube_split_1-budget_5-seed_42:tmp"
trained_classifier_artifact_name: "masked_mlp_classifier-cube_split_1:tmp"
output_artifact_aliases: ["tmp"]
seed: 42
device: "cuda"
eval_only_n_samples: null
batch_size: 1
