experiment_id: "tmp" # set this every time at the command line
dataset_artifact_aliases:
    AFAContext: "oct8a"
    cube: "oct8a"
dataset_splits: [1, 2]
dataset_split_mode: "validation" # switch to test at the end
# In case some model needed pretraining after adding soft budget
pretrained_model_aliases:
    shim2018: "KDD"
    zannone2019: "KDD"
    kachuee2019: "oct9a"
classifier: "masked_mlp_classifier"
classifier_artifact_aliases:
    AFAContext: "KDD"
    cube: "KDD"
validate_artifacts: false # whether to ensure that classifier is trained on the exact same data
seeds: [42] # use more seeds at the end
train_device: "cpu"
eval_device: "cpu"
cost_params_per_method:
    # randomdummy: [0.1, 0.3]
    # sequentialdummy: [0.1, 0.3]
    shim2018: [0.1, 0.001, 0.00001]
    zannone2019: [0.1, 0.001, 0.00001]
    kachuee2019: [0.1, 0.001, 0.00001]
smoke_test: true
