# EXPERIMENT_ID = config[
#     "experiment_id"
# ]  # affects both artifact aliases and where results are stored
experiment_id: "oct9a"
dataset_artifact_aliases:
    AFAContext: "oct8a"
    cube: "oct8a"
dataset_splits: [1, 2]
dataset_split_mode: "validation" # switch to test at the end
classifier: "masked_mlp_classifier"
classifier_artifact_alias: "KDD"
validate_artifacts: false # whether to ensure that classifier is trained on the exact same data
seeds: [1, 2]
train_device: "cpu"
eval_device: "cpu"
cost_params_per_method:
    # randomdummy: [0.1, 0.3]
    # sequentialdummy: [0.1, 0.3]
    shim2018: [0.1, 0.001, 0.00001]
    kachuee2019: [0.1, 0.001, 0.00001]
has_pretrain_stage:
    # randomdummy: false
    # sequentialdummy: false
    shim2018: true
    kachuee2019: true
pretrain_alias: "KDD"
smoke_test: true
