dataset_artifact_name: "bank_marketing_split_1:test"
evaluate_final_performance: true
batch_size: 128
epochs: 300  # Similar to diabetes
limit_train_batches: null
limit_val_batches: null
min_masking_probability: 0.0
max_masking_probability: 0.9
eval_only_n_samples: null
lr: 1e-3
seed: 42
device: "cuda"
num_cells: [128, 128]
dropout: 0.1
