dataset_artifact_name: "cube_split_1:tmp"
batch_size: 128
epochs: 1000
min_masking_probability: 0.0
max_masking_probability: 0.9
eval_only_n_samples: null
lr: 1e-3
seed: 42
device: "cuda"
num_cells: [128, 128]
dropout: 0.1
