dataset_artifact_name: "MNIST_split_1:tmp"
evaluate_final_performance: true
batch_size: 128
epochs: 1
min_masking_probability: 0.75
max_masking_probability: 0.99
eval_only_n_samples: 100
lr: 1e-3
seed: 42
device: "cuda"
num_cells: [128, 128]
dropout: 0.1
