dataset_artifact_name: "physionet_split_1:tmp"
evaluate_final_performance: true
batch_size: 128
epochs: 100 # physionet is unbalanced and therefore very prone to overfit
limit_train_batches: null
limit_val_batches: null
min_masking_probability: 0.0
max_masking_probability: 0.9
eval_only_n_samples: null
lr: 1e-3
seed: 42
device: "cuda"
num_cells: [128, 128]
dropout: 0.1
