supervised_learning:
  batch_size: 128 # shim2018 paper
  max_epochs: 1_000_000_000 # upper bound, we use early stopping to stop earlier
  checkpoint_earliest_batch: 500
  early_stopping_min_batches: 1000
  early_stopping_patience: 50
  early_stopping_min_delta: 1e-3
  val_check_interval: 100 # validate every n batches
  limit_train_batches: null  # only used for smoke tests
  limit_val_batches: null  # only used for smoke tests
