dataset_artifact_name: "diabetes_split_1:latest"

batch_size: 128
hard_budget: 20

selector:
  lr: 0.001
  nepochs: 250
  num_cells: [128, 128]
  patience: 5

classifier:
  lr: 0.001
  nepochs: 250
  num_cells: [128, 128]