hydra:
  searchpath:
    - file://extra/conf
    - file://extra/conf/global

defaults:
  - hydra: custom
  - /components/initializers@initializer: ???
  - /components/unmaskers@unmasker: ???
  - _self_
  - optional experiment@_global_: ???
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - override hydra/launcher: custom_slurm

train_dataset_bundle_path: ???
val_dataset_bundle_path: ???
classifier_bundle_path: ???
pretrained_model_bundle_path: ???
save_path: ???
device: null
seed: null

soft_budget_param: null
use_wandb: false
smoke_test: false
ipw_mode: "none"
ipw_min_propensity: 0.001
ipw_max_weight: 10.0
ipw_normalize_weights: true
