dataset:
  artifact_name: "FashionMNIST_split_1:May26"
batch_size: 128
epochs: 20

device: cuda
seed: 42
lr: 1e-3
max_masking_probability: 0.99
encoder:
  output_size: 128
  reading_block_cells: [128, 128]
  writing_block_cells: [128, 128]
  memory_size: 128
  processing_steps: 5
  dropout: 0.1
classifier:
  num_cells: [128, 128]

