dataset_artifact:
  name: "cube_split_1:May26"
batch_size: 128
epochs: 50

device: cuda
seed: 42
lr: 1e-4
max_masking_probability: 0.9
encoder:
  output_size: 16
  reading_block_cells: [32, 32]
  writing_block_cells: [32, 32]
  memory_size: 16
  processing_steps: 5
  dropout: 0.1
classifier:
  num_cells: [32, 32]

