hydra:
  searchpath:
    - file://conf/global

defaults:
  - _self_
  - dataset@_global_: cube
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - override hydra/launcher: custom_slurm

# Default settings below, but fine-tune for each dataset
dataset_artifact_name: "cube_split_1:tmp"
output_artifact_aliases: ["tmp"]
batch_size: 128
epochs: 3000

device: cuda
seed: 42
lr: 1e-3
min_masking_probability: 0.0
max_masking_probability: 0.9
encoder:
  output_size: 128
  reading_block_cells: [128, 128]
  writing_block_cells: [128, 128]
  memory_size: 128
  processing_steps: 5
  dropout: 0.1
classifier:
  num_cells: [128, 128]
