hydra:
  searchpath:
    - file://extra/conf
    - file://extra/conf/global

defaults:
  - train_odin
  - hydra: custom
  - /components/initializers@initializer: ???
  - /components/unmaskers@unmasker: ???
  - /components/mdps@mdp: default
  - /components/rl_training_loops@rl_training_loop: default
  - _self_
  - optional experiment@_global_: ???
  - override hydra/job_logging: output_dir_colorlog
  - override hydra/hydra_logging: colorlog
  - override hydra/launcher: custom_slurm

train_dataset_bundle_path: ???
val_dataset_bundle_path: ???
pretrained_model_bundle_path: ???
classifier_bundle_path: null # not needed for this method, but pipeline passes it to us
save_path: ???
# initializer set as component
# unmasker set as component
mdp:
  hard_budget: ???
# rl_training_loop set as component
soft_budget_param: ???

agent:
    lmbda: 0.75 # not specified by odin, same as jafa

    clip_epsilon: 0.2 # not specified by odin
    entropy_bonus: True # not specified by odin
    entropy_coef: 0.01 # not specified by odin
    critic_coef: 1.0 # not specified by odin
    loss_critic_type: "smooth_l1" # not specified by odin

    num_epochs: 1 # same as jafa
    lr: 1e-3 # not specified by odin
    max_grad_norm: 9001 # not specified by odin

    # value_num_cells: [32, 32] # same complexity as jafa
    value_num_cells: [] # odin
    value_dropout: 0.0 # not specified by odin
    # policy_num_cells: [32, 32] # same complexity as jafa
    policy_num_cells: [] # odin
    policy_dropout: 0.0 # not specified by odin
    gamma: 1.0
    use_action_availability: false
additional_generation_fraction: 0.0
generation_batch_size: 100
seed: null
use_wandb: false
smoke_test: false
device: null

# Alias arguments, only to implement interface assumed by snakemake
hard_budget: null
