hydra:
  searchpath:
    - file://conf/global

defaults:
  - _self_
  - dataset@_global_: cube
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - override hydra/launcher: custom_slurm

dataset_artifact_name: "cube_split_1:tmp"
output_artifact_aliases: ["tmp"]
evaluate_final_performance: true
batch_size: 128
epochs: 100
limit_train_batches: null
limit_val_batches: null

min_masking_probability: 0.0
max_masking_probability: 0.9
eval_only_n_samples: null
lr: 1e-3
seed: 42
device: "cuda"
num_cells: [128, 128]
dropout: 0.1
