dataset_artifact_name: "cube_split_1:tmp"
batch_size: 128
epochs: 100
max_masking_probability: 0.9
lr: 1e-3
seed: 42
device: "cuda"
num_cells: [128, 128]
dropout: 0.1

defaults:
  - override hydra/launcher: submitit_slurm

hydra:
  launcher:
    timeout_min: 1440  # 24 hours

    partition: alvis
    account: NAISS2025-22-448

    additional_parameters:
      gres: gpu:T4:1
