dataset_artifact_name: "cube_split_1:tmp"
output_artifact_aliases: ["tmp"]
evaluate_final_performance: true
batch_size: 128
epochs: 100
max_masking_probability: 0.9
lr: 1e-3
seed: 42
device: "cuda"
num_cells: [128, 128]
dropout: 0.1
