executor: slurm
latency-wait: 30 # seconds

default-resources:
  slurm_partition: vera
  slurm_account: C3SE2026-1-12
  runtime: 120 # minutes
  cpus_per_task: 1
  mem_mb: 4000

set-resources:
  pretrain_model:
    runtime: 6000 # 100 hours
  train_method_with_pretrained_model:
    runtime: 6000 # 100 hours
  train_method_without_pretrained_model:
    runtime: 6000 # 100 hours

  # Although the merged eval dataframes "only" take up less than 1Gb, opening them can use a lot more
  split_by_classifier_type:
    cpus_per_task: 10
  plot_eval_perf:
    cpus_per_task: 10
  plot_eval_actions:
    cpus_per_task: 10
