executor: slurm
jobs: 9001
latency-wait: 30 # seconds

default-resources:
  runtime: 120 # minutes
  slurm_partition: alvis
  slurm_account: NAISS2025-22-1420
  mem_mb: 0 # Only memory attribute that works
  slurm_extra: "--gres=gpu:T4:1"

set-resources:
  pretrain_model:
    runtime: 600 # 10 hours
  train_method_with_pretrained_model:
    runtime: 600 # 10 hours
  train_method_without_pretrained_model:
    runtime: 600 # 10 hours
  eval_method:
    runtime: 600 # 10 hours
  eval_method_shielded:
    runtime: 600 # 10 hours
  eval_method_dualized:
    runtime: 600 # 10 hours
