executor: slurm
jobs: 50
latency-wait: 30

default-resources:
  runtime: 120
  slurm_partition: alvis
  slurm_account: NAISS2025-22-448
  mem_mb: 0
  slurm_extra: "--gres=gpu:T4:1"

set-resources:
  train_classifier:
    runtime: 1440
  pretrain_model:
    runtime: 600
  train_method_with_pretrained_model:
    runtime: 1440
    # slurm_extra: "--gres=gpu:A40:1"
  train_method_without_pretrained_model:
    runtime: 600
  eval_method:
    runtime: 1440
