executor: slurm
jobs: 50
latency-wait: 30

default-resources:
  runtime: 120
  slurm_partition: alvis
  slurm_account: NAISS2025-22-448
  mem_mb: 0
  slurm_extra: "--gres=gpu:T4:1"

set-resources:
  pretrain_model:
    runtime: 600
  train_method_with_pretrained_model:
    runtime: 600
  train_method_with_foreign_pretrained_model:
    runtime: 10
  train_method_without_pretrained_model:
    runtime: 600
  eval_method_hard:
    runtime: 1440
  eval_method_soft:
    runtime: 1440
