snakefile: workflow/snakefiles/orchestration/pipeline.smk

configfile:
  - workflow/conf/eval_hard_budgets/all.yaml
  - workflow/conf/methods/all.yaml
  - workflow/conf/method_sets/all.yaml
  - workflow/conf/method_options/all.yaml
  - workflow/conf/pretrain_mappings/all.yaml
  - workflow/conf/soft_budget_params/all.yaml
  - workflow/conf/unmaskers/all.yaml
  - workflow/conf/classifier_names/all.yaml
  - workflow/conf/datasets/all.yaml
  - workflow/conf/execution/all.yaml
